services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"  # UI do Jaeger
      - "4317:4317"    # OTLP gRPC
      - "4318:4318"    # OTLP HTTP

  mysite:
    build: .
    ports:
      - "8080:8080"
    environment:
      - OTEL_SERVICE_NAME=mysite
      - OTEL_LOG_LEVEL=debug
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_EXPORTER_OTLP_INSECURE=true
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
      - OTEL_TRACES_EXPORTER=otlp
      - DB_HOST=db
      - DB_USER=mysite
      - DB_PASSWORD=password123
      - DB_NAME=mysite
      
    depends_on:
      - jaeger
      - prometheus
      - db

  db:
    image: mariadb
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=password123
      - MARIADB_USER=mysite
      - MARIADB_PASSWORD=password123
      - MARIADB_DATABASE=mysite
    ports:
      - "3306:3306"


  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus
      - jaeger

volumes:
  grafana-storage:
