apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mysite
spec:
  replicas: 4
  selector: 
    matchLabels:
      app: mysite
  template: 
    metadata:
      labels:
        app: mysite
    spec: 
      containers:
        - name: mysite
          image: julianorib/mysite:v2.0
          ports:
            - name: http-web
              containerPort: 8080
          volumeMounts:
          - name: vol
            mountPath: /opt
      volumes:
        - name: vol
          persistentVolumeClaim:
            claimName: mysite
