apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mysite
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: mysite
  template: 
    metadata:
      labels:
        app: mysite
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "8080"
        prometheus.io/interval: '30s'
    spec: 
      containers:
        - name: mysite
          image: julianorib/mysite:v2.0
          ports:
            - name: http-web
              containerPort: 8080 