apiVersion: v1
kind: Service
metadata:
<<<<<<< HEAD
  name: mysite-service
  labels:
   release: monitoring
=======
  name: mysite
  labels:
    app: mysite
>>>>>>> 131b1e19431bf65bafc8ba67246e35f07e09b897
spec:
  selector:
    app: mysite
  ports:
    - name: http-web
      port: 80
      targetPort: 8080
  type: LoadBalancer