apiVersion: v1
kind: Service
metadata:
  name: mysite-service
#  labels:
#    release: monitoring
spec:
  selector:
    app: mysite
  ports:
    - name: http-web
      port: 80
      targetPort: 8080
  type: LoadBalancer