# apiVersion: monitoring.coreos.com/v1
# kind: ServiceMonitor
# metadata:
#   name: mysite-monitor
#   labels:
#     release: monitoring
# spec:
#   endpoints:
#     - port: http-web
#       path: /metrics
#   selector:
#     matchLabels:
#       app: mysite