apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mysite
  labels:
    release: prometheus
spec:
  endpoints:
    - port: http-web
      path: /metrics
  selector:
    matchLabels:
      app: mysite
