apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mysite
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: mysite
  endpoints:
    - port: http-web
      path: /metrics
