apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mysite-deployment
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: mysite
  template: 
    metadata:
      labels:
        app: mysite
    spec: 
      containers:
        - name: mysite
          image: julianorib/mysite:v2.0
          ports:
            - name: web
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mysite-service
spec:
  selector:
    app: mysite
  ports:
    - name: web
      port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: mysite-prom
spec:
  type: ClusterIP
  selector:
    app: mysite
  ports:
    - name: http-web
      port: 8080
      targetPort: http-web
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mysite
spec:
  endpoints:
    - port: http-web
      path: /metrics
  namespaceSelector:
    matchNames:
    - mysite2
  selector:
    matchLabels:
      app: mysite
